# Paths
raw_data_path: './data/raw/'
meta_data_path: './data/raw/meta_data.csv'
processed_data_path: './data/processed/'

# Pytorch

# Game data
games: ['breakout']

# Dataset parameters
batch_size: 32
num_workers: 1

# Data pre-processing
size_x: 80
size_y: 105
train_sub: ['J']
test_sub: ['K']
grey_scale : True

# Data writer parameters
data_writer:
  shard_write: False
  shard_maxcount: 6250
  data_write_freq: 3
